# -*- coding: utf-8 -*-
"""
/***************************************************************************
 classeClimaOWM
                                 A QGIS plugin
 Plugin que mostra o clima de um ponto ou região em um Mapa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-20
        copyright            : (C) 2024 by Direto ao Python
        email                : diretoaopython@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load classeClimaOWM class from file classeClimaOWM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dpyClimaOWM import classeClimaOWM
    return classeClimaOWM(iface)
